### ISSUE TITLE
Test run fails if done is passed

### ISSUE THREAD

**Issue by Tsarar** [UziTech/jasmine-expect-count#127]
Hi!

I've tried to use this library but I can see the following errors:

1) Chrome Headless 87.0.4280.88 (Windows 10) Unit tests for *** FAILED
        TypeError: done is not a function

2) 25 12 2020 19:25:21.371:WARN [reporter]: SourceMap position not found for trace: TypeError: done is not a function
    at <Jasmine>
    at http://localhost:9876/base/test/index.js?986c9619bf8315c8f810e9cf331a41e95ce5f13c:331586:9
    at <Jasmine>
    at fulfilled (http://localhost:9876/base/test/index.js?986c9619bf8315c8f810e9cf331a41e95ce5f13c:331081:58)

Test example:

    it("Test", async (done) => {
		// Arrange
		let spyFuncArgument = jasmine.createSpy("spyFunc");
		let mockArgument = { value: "value" } as any;
		const testParam = "value";
		const dataProviderInstance = DataProviderFactory.getInstance().getDataProvider();

		spyOn(dataProviderInstance, "someMethod").and.returnValue(Promise.reject(mockArgument));
		spyOn(Utility, "setAriaLiveAlert");

		// Act
		await TestClass.testMethod(testParam)(spyFuncArgument);

		// Assert
		expect(dataProviderInstance.someMethod).toHaveBeenCalledWith(testParam);
		expect(spyFuncArgument).toHaveBeenCalledWith(TestClass.someMethod1(true));
		expect(spyFuncArgument).toHaveBeenCalledWith(TestClass.someMethod2(mockArgument, Constants.EMPTYSTRING));
		expect(spyFuncArgument).toHaveBeenCalledWith(TestClass.someMethod3(false));
		expect(Utility.setAriaLiveAlert).toHaveBeenCalled();
		expect(Logger.info).not.toHaveBeenCalled();
		done();
	});

I believe that this library currently is not working with tests, which are using done() method properly.

**Comment by UziTech** [comment]
Thanks for reporting this. Yes it looks like it was erroring when done was used in a test. This should be fixed in the next version.
